# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/hdmi_inout_bd_rgb2dvi_0_3.xci
# IP: The module: 'hdmi_inout_bd_rgb2dvi_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/hdmi_inout_bd_rgb2dvi_0_3.xci
# IP: The module: 'hdmi_inout_bd_rgb2dvi_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SDUP_proj/hdmi_inout_kopiaZapasowa/hdmi_inout_kopiaZapasowa/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_3/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_rgb2dvi_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
