# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/test/MTM_SDUP_project/BETSS/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_xbar_2/hdmi_inout_bd_xbar_2.xci
# IP: The module: 'hdmi_inout_bd_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/test/MTM_SDUP_project/BETSS/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_xbar_2/hdmi_inout_bd_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/DELL/Desktop/test/MTM_SDUP_project/BETSS/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_xbar_2/hdmi_inout_bd_xbar_2.xci
# IP: The module: 'hdmi_inout_bd_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/test/MTM_SDUP_project/BETSS/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_xbar_2/hdmi_inout_bd_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
