# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z7.xdc

# Block Designs: bd/hdmi_inout_bd/hdmi_inout_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_inout_bd || ORIG_REF_NAME==hdmi_inout_bd} -quiet] -quiet

# IP: bd/hdmi_inout_bd/ip/hdmi_inout_bd_dvi2rgb_0_0/hdmi_inout_bd_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_inout_bd_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_inout_bd_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hdmi_inout_bd/ip/hdmi_inout_bd_rgb2dvi_0_0/hdmi_inout_bd_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_inout_bd_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_inout_bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/hdmi_inout_bd/ip/hdmi_inout_bd_clk_wiz_0_0/hdmi_inout_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_inout_bd_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_inout_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_inout_bd/ip/hdmi_inout_bd_xlconstant_0_0/hdmi_inout_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_inout_bd_xlconstant_0_0 || ORIG_REF_NAME==hdmi_inout_bd_xlconstant_0_0} -quiet] -quiet

# XDC: bd/hdmi_inout_bd/hdmi_inout_bd_ooc.xdc
