# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1.xci
# IP: The module: 'hdmi_inout_bd_v_tc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_v_tc_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_v_tc_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1.xci
# IP: The module: 'hdmi_inout_bd_v_tc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_v_tc_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/BETSS/hdmi_inout_po_konsultacji/hdmi_inout/hdmi_inout.srcs/sources_1/bd/hdmi_inout_bd/ip/hdmi_inout_bd_v_tc_0_1/hdmi_inout_bd_v_tc_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_inout_bd_v_tc_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
